const numberButtons = document.querySelectorAll('[data-number]')
const operationButtons = document.querySelectorAll('[data-operation]')
const equalsButtons = document.querySelector('[data-equals]')
const equalsButtons = document.querySelector('[data-equals]')
const equalsButtons = document.querySelector('[data-equals]')
const equalsButtons = document.querySelector('[data-equals]')